### ISSUE TITLE
How to use it from CLI

### ISSUE THREAD

**Issue by munrocket** [wessberg/cjs-to-esm-transformer#1]
Why you not explain how to use it from CLI?
We need a tool to convert all repo with CJS to ESM.

**Comment by wessberg** [comment]
Hi there,

If you intend to use this library to convert from CJS to ESM on an existing _Typescript_ project, you're out of luck since this is a Custom Transformer for Typescript and as such will be used in the emit phase while generating .js from your .ts sources.

That said, theoretically, if your project is written in JavaScript, you _could_ run it through the TypeScript compiler, using this Custom Transformer, and have it emit transformed output files to another directory.

**Comment by wessberg** [comment]
Hi there,

I actually went and implemented CLI support just now. It has been released in v0.0.10.
See [this section](https://github.com/wessberg/cjs-to-esm-transformer/tree/master#cli) for instructions.

Basically, you can run `npx cjstoesm transform <inputGlob> <outDir>` to transform all of your source files matched by `<inputGlob>` from CJS to ESM and emit them to `<outDir>`.

If you have any issues, feel free to get back to me.
